// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzwbfvlpthuawzxiwvpy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6d2JmdmxwdGh1YXd6eGl3dnB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMTAyNzIsImV4cCI6MjA2MzY4NjI3Mn0.BNG91GjjvW8krN_1OU7MnHa_r3JYkw5VjI8W1-i4ciE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
