// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qthdycwawrplemcqyqmt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0aGR5Y3dhd3JwbGVtY3F5cW10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMDYyODgsImV4cCI6MjA2MzY4MjI4OH0.PU-6Q2jS10IlEKw0yoazhzahBYFxzpwuHx0d6kEQD-U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);